### ISSUE TITLE
ModuleNotFoundError: No module named 'peak_detection'

### ISSUE THREAD

**Issue by xhain** [johnglover/simpl#1]
Dear Developers,

thank you for providing this open source code for sinusoidal modeling.
I followed all the steps described in the setup and installation procedure but couldn't get it to run.
There were no issues displayed when I compiled the code - but it seems that some modules can't be found/imported correctly.

The 'peak_detection' for example is in the correct directory and has the full file name:
'peak_detection.cpython-37m-darwin.so'

Maybe I'm missing something here. I hope somebody can help me out.
I'm using Python 3 on OSX.

Thank you for your time.
Max

**Comment by bwhitman** [comment]
I filed PR #3 to fix this for me, if it still helps

**Comment by johnglover** [comment]
Appears to be resolved thanks to Brian's PR.
